name: 'Maven Release Action'
description: 'Build and release a Maven project'
outputs:
  version:
    description: 'The release version'
    value: ${{ steps.resolve_version.outputs.version }}
inputs:
  deploy-actor:
    description: 'user to authenticate at the artifact repository'
    required: true
  deploy-token:
    description: 'password to authenticate at the artifact repository'
    required: true
  deploy-server:
    description: 'Dist server id, e.g. central, github, nexus'
    required: true
  gpg-passphrase:
    description: 'The gpg private key passphrase'
    required: true
  gpg-private-key:
    description: 'The encoded gpg private key'
    required: true
  java-version:
    description: 'The version of Java to build and release with'
    default: '17'
  maven-release-args:
    description: 'Additional arguments to pass to the Maven release command-line'
    default: ''
  maven-profiles:
    description: 'Maven profiles to activate, comma-delimited'
    default: ''
  dry-run:
    description: "Perform a dry run release"
    default: 'false'

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true

    - shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_ACTOR_ID: ${{ github.actor_id }}
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

    - shell: bash
      id: resolve_vars
      run: |
        . "${GITHUB_ACTION_PATH}/include.sh"
        # Convert spaces to commas in the profiles string
        declare -a _profiles=( ${{ inputs.maven-profiles }} )
        MAVEN_PROFILES=$(IFS=, ; echo "${_profiles[*]}")
        printf '%s\n' \
          "DEPLOY_SERVER=${{ inputs.deploy-server }}" \
          "MAVEN_PROFILES=${MAVEN_PROFILES}" \
          >> $GITHUB_ENV
        # Build the list of SDKs to install
        {
          echo 'JAVA_SDK_VERSIONS<<EOF'
          calcJavaVers ${{ inputs.java-version }}
          echo EOF
        } >> "$GITHUB_ENV"

    - uses: actions/setup-java@v5
      with:
        server-id: ${{ inputs.deploy-server }}
        server-username: DEPLOY_ACTOR
        server-password: DEPLOY_TOKEN
        distribution: 'temurin'
        java-version: "${{ env.JAVA_SDK_VERSIONS }}"
        #cache: 'maven'
        #cache-dependency-path: 'sub-project/pom.xml'

    - shell: bash
      id: resolve_version
      run: |
        VERSION="$(./mvnw -e help:evaluate -q -DforceStdout -Dexpression=project.version)"
        VERSION="${VERSION%-SNAPSHOT}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - shell: bash
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        DEPLOY_ACTOR: ${{ inputs.deploy-actor }}
        DEPLOY_TOKEN: ${{ inputs.deploy-token }}
        MAVEN_GPG_KEY: ${{ inputs.gpg-private-key }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        MAVEN_RELEASE_ARGS: ${{ inputs.maven-release-args }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        export GPG_TTY=$(tty)
        declare -a goals_=( "release:prepare" )
        if [ "${DRY_RUN}" != "true" ] ; then goals_+=( "release:perform" ) ; fi
        declare -a envargs_=( -B -ntp -e -s "${GITHUB_ACTION_PATH}/settings.xml" )
        if [ -n "${MAVEN_PROFILES}" ] ; then envargs_+=( "-P${MAVEN_PROFILES}" ) ; fi
        export MAVEN_ARGS="${envargs_[*]}"
        declare -a cliargs_=( )
        cliargs_+=( "-DpushChanges=false" )
        cliargs_+=( "-DlocalCheckout=true" )
        cliargs_+=( "-DtagNameFormat=v@{project.version}" )
        cliargs_+=( "-DscmCommentPrefix=[GitHub] [no ci]" )
        echo "Invoking:" ./mvnw ${MAVEN_RELEASE_ARGS} "${cliargs_[@]}" "${goals_[@]}"
        ./mvnw ${MAVEN_RELEASE_ARGS} "${cliargs_[@]}" "${goals_[@]}"

    - shell: bash
      if: ${{ inputs.dry-run != 'true' && success() }}
      run: |
        ${EXEC_PREFIX} git push
        ${EXEC_PREFIX} git push --tags
