name: 'Maven Release Action'
description: 'Build and release a Maven project'
outputs:
  version:
    description: 'The release version'
    value: ${{ steps.resolve_version.outputs.version }}
inputs:
  deploy-actor:
    description: 'user to authenticate at the artifact repository'
    required: true
  deploy-token:
    description: 'password to authenticate at the artifact repository'
    required: true
  deploy-server:
    description: 'Dist server id, e.g. central, github, nexus'
    required: true
  gpg-passphrase:
    description: 'The gpg private key passphrase'
    required: true
  gpg-private-key:
    description: 'The encoded gpg private key'
    required: true
  java-version:
    description: 'The version of Java to build and release with'
    default: '17'
  github-actor:
    description: 'The github server username, required for tag commit permission'
    default: ${{ github.actor }}
  github-token:
    description: 'The github server password, required for tag commit permission'
    default: ${{ github.token }}
  maven-profiles:
    description: 'Maven profiles to activate, comma-delimited'
    default: ''
  dry-run:
    description: "Perform a dry run release"
    default: 'false'

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ inputs.github-token }}

    - shell: bash
      run: |
        git config user.name github-actions[bot]
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - shell: bash
      id: resolve_vars
      run: |
        . "${GITHUB_ACTION_PATH}/include.sh"
        # Convert spaces to commas in the profiles string
        declare -a _profiles=( ${{ inputs.maven-profiles }} )
        MAVEN_PROFILES=$(IFS=, ; echo "${_profiles[*]}")
        printf '%s\n' \
          "DEPLOY_SERVER=${{ inputs.deploy-server }}" \
          "MAVEN_PROFILES=${MAVEN_PROFILES}" \
          >> $GITHUB_ENV
        # Build the list of SDKs to install
        {
          echo 'JAVA_SDK_VERSIONS<<EOF'
          calcJavaVers ${{ inputs.java-version }}
          echo EOF
        } >> "$GITHUB_ENV"

    - uses: actions/setup-java@v5
      with:
        server-id: ${{ inputs.deploy-server }}
        server-username: DEPLOY_ACTOR
        server-password: DEPLOY_TOKEN
        distribution: 'temurin'
        java-version: "${{ env.JAVA_SDK_VERSIONS }}"
        #cache: 'maven'
        #cache-dependency-path: 'sub-project/pom.xml'

    - shell: bash
      id: resolve_version
      run: |
        VERSION="$(mvn -e help:evaluate -q -DforceStdout -Dexpression=project.version)"
        VERSION="${VERSION%-SNAPSHOT}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - shell: bash
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        DEPLOY_ACTOR: ${{ inputs.deploy-actor }}
        DEPLOY_TOKEN: ${{ inputs.deploy-token }}
        MAVEN_GPG_KEY: ${{ inputs.gpg-private-key }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        declare -a goals_=( "release:prepare" )
        if [ "${DRY_RUN}" = "true" ] ; then goals_+=( "release:perform" ) fi
        declare -a mvnArgs_=( "-B" )
        declare -a argArgs_=( "-ntp" )
        argArgs_+=( "-s" "${GITHUB_ACTION_PATH}/settings.xml")
        if [ -n "${MAVEN_PROFILES}" ] ; then
          argArgs_+=( "-P${MAVEN_PROFILES}" )
          mvnArgs_+=( "-DreleaseProfiles=${MAVEN_PROFILES}" )
          mvnArgs_+=( "-DpreparationProfiles=${MAVEN_PROFILES}" )
        fi
        mvnArgs_+=( "${argArgs_[@]}" )
        mvnArgs_+=( "-Darguments=${argArgs_[*]}" )
        mvnArgs_+=( "-DpushChanges=false" )
        mvnArgs_+=( "-DlocalCheckout=true" )
        mvnArgs_+=( "-DtagNameFormat=v@{project.version}" )
        mvnArgs_+=( "-DscmCommentPrefix=[GitHub] [no ci]" )
        export GPG_TTY=$(tty) && mvn "${mvnArgs_[@]}" "${goals_[@]}"

    - shell: bash
      if: ${{ inputs.dry-run != 'true' && success() }}
      run: |
        ${EXEC_PREFIX} git push
        ${EXEC_PREFIX} git push --tags
