name: Git Initialize User
description: Configure the Git user.name and user.email which enables committing
author: Patrick Woodworth
branding:
  icon: chevron-up
  color: yellow
inputs:
  git-excludes:
    description: 'Git exclude patterns'
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      env:
        GIT_EXCLUDE_PATTERNS: ${{ inputs.git-excludes }}
      # language="shell script"
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        if [ -n "${GIT_EXCLUDE_PATTERNS}" ]; then
          printf '%s\n' ${GIT_EXCLUDE_PATTERNS} >> ".git/info/exclude"
        fi
