name: 'Tag Next Version'
description: 'Release using semtag tool'
outputs:
  release_version:
    description: "The released version"
    value: ${{ steps.resolve_version.outputs.next_version }}
  major_version:
    description: "The major version"
    value: ${{ steps.resolve_version.outputs.major_version }}
inputs:
  github-actor:
    description: "Required for permission to tag the repo."
    default: ${{ github.actor }}
  github-token:
    description: "Required for permission to tag the repo."
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ inputs.github-token }}

    - uses: emergentdotorg/github-actions/git-init-user@main

    - shell: bash
      id: resolve_version
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      # language="shell script"
      run: |
        next_version="$( source "${GITHUB_ACTION_PATH}/semtag" final -pfos "auto" )"
        next_version_tag="v${next_version}"
        major_version="${next_version%%.*}"
        major_version_tag="v${major_version}"
        printf '%s\n' \
          "next_version=${next_version}" \
          "next_version_tag=${next_version_tag}" \
          "major_version=${major_version}" \
          "major_version_tag=${major_version_tag}" \
          >> $GITHUB_OUTPUT

    - shell: bash
      id: apply_tags
      env:
        NEXT_VERSION_TAG: ${{ steps.resolve_version.outputs.next_version_tag }}
        MAJOR_VERSION_TAG: ${{ steps.resolve_version.outputs.major_version_tag }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      # language="shell script"
      run: |
        next_tag_output="$( source "${GITHUB_ACTION_PATH}/semtag" final -v "${NEXT_VERSION_TAG}" )"
        rt=$? ; echo "${next_tag_output}" ; [[ $rt -eq 0 ]] || exit $rt
        major_tag_output="$( source "${GITHUB_ACTION_PATH}/semtag" final -v "${MAJOR_VERSION_TAG}" )"
        rt=$? ; echo "${next_tag_output}" ; [[ $rt -eq 0 ]] || exit $rt
