name: 'Java Maven Environment Setup'
description: 'Setup Java Environment'
inputs:
  deploy-server:
    description: >
      ID of the distributionManagement repository in the pom.xml file. Default is `github`
    required: false
    default: 'github'
  deploy-username-env:
    description: >
      Environment variable name for the username for authentication
      to the Apache Maven repository. Default is $GITHUB_ACTOR'
    required: false
    default: 'GITHUB_ACTOR'
  deploy-password-env:
    description: >
      Environment variable name for password or token for
      authentication to the Apache Maven repository. Default is $GITHUB_TOKEN'
    required: false
    default: 'GITHUB_TOKEN'
  github-username-env:
    description: >
      Environment variable name for the username for authentication
      to the source repository. Default is $GITHUB_ACTOR'
    required: false
    default: 'GITHUB_ACTOR'
  github-password-env:
    description: >
      Environment variable name for password or token for
      authentication to the source repository. Default is $GITHUB_TOKEN'
    required: false
    default: 'GITHUB_TOKEN'
  gpg-passphrase-env:
    description: >
      Environment variable name for the GPG private key passphrase. 
      Default is $GPG_PASSPHRASE.
    required: false
    default: 'GPG_PASSPHRASE'
  gpg-private-key:
    description: 'GPG private key to import. Default is empty string.'
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  maven-version:
    description: 'Maven version'
    required: true
    default: '3.9.9'

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.github-token }}

    - name: Setup Git Config
      shell: bash
      # language="shell script"
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        printf '%s\n' \
          '/github-actions/' \
          '/gha-creds*.json' \
          '/settings.xml' \
          '/settings-global.xml' \
          '/toolchains.xml' \
          >> ".git/info/exclude"

    - name: Install Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: 'Setup Java'
      uses: actions/setup-java@v4
      with:
        server-id: ${{ inputs.deploy-server }}
        server-username: ${{ inputs.deploy-username-env }}
        server-password: ${{ inputs.deploy-password-env }}
        gpg-passphrase: ${{ inputs.gpg-passphrase-env }}
        gpg-private-key: ${{ inputs.gpg-private-key }}
        distribution: 'temurin'
        java-version: |
          8
          11
          17
        mvn-toolchain-id: |
          temurin_8
          temurin_11
          temurin_17

    - uses: s4u/maven-settings-action@v3.1.0
      if: ${{ inputs.deploy-server != 'github' && success() }}
      with:
        path: '$HOME/.m2/settings-global.xml'
        githubServer: 'false'
        servers: >
          [{
            "id": "github",
            "username": "${env.${{ inputs.github-username-env }}}",
            "password": "${env.${{ inputs.github-password-env }}}"
          }]

    - name: 'Verify Java and Maven'
      shell: bash
      # language="shell script"
      run: |
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "JAVA_HOME_8_X64: $JAVA_HOME_8_X64"
        echo "JAVA_HOME_11_X64: $JAVA_HOME_11_X64"
        echo "JAVA_HOME_17_X64: $JAVA_HOME_17_X64"
        mvn -version
        catIfExists() {
          if [ -f "$1" ]; then
            cat "$1"
          else
            echo "WARNING: File $1 does not exist"
          fi
        }
        catIfExists "$HOME/.m2/settings.xml"
        catIfExists "$HOME/.m2/settings-global.xml"
        catIfExists "$HOME/.m2/toolchains.xml"
