name: Reusable Maven Release

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      version:
        description: "The new release version"
        value: ${{ jobs.release.outputs.release_version }}
    inputs:
      java-version:
        description: 'JDK version to build with'
        type: string
        required: true
      deploy-server:
        description: 'Maven dist mgmt server-id'
        type: string
        default: 'emergent-nexus'
      maven-profiles:
        description: 'Maven profiles to activate, comma-delimited'
        type: string
        default: ''
      use-release-plugin:
        description: 'Whether to use the release plugin or try a modern process'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_version: ${{ steps.resolve_version.outputs.release_version }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Resolve Vars
        id: resolve_vars
        shell: bash
        env:
          DEPLOY_SERVER: ${{ inputs.deploy-server }}
          DEPLOY_CENTRAL_ACTOR: ${{ secrets.deploy_central_actor }}
          DEPLOY_CENTRAL_TOKEN: ${{ secrets.deploy_central_token }}
          DEPLOY_GITHUB_ACTOR: 'emergentbot'
          DEPLOY_GITHUB_TOKEN: ${{ secrets.emergentbot_deploy_token }}
          DEPLOY_NEXUS_ACTOR: ${{ secrets.deploy_nexus_actor }}
          DEPLOY_NEXUS_TOKEN: ${{ secrets.deploy_nexus_token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        # language="shell script"
        run: |
          case "${DEPLOY_SERVER}" in
            central)
              DEPLOY_ACTOR="${DEPLOY_CENTRAL_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_CENTRAL_TOKEN}"
              ;;
            github)
              DEPLOY_ACTOR="${{ github.actor }}"
              DEPLOY_TOKEN="${{ github.token }}"
              ;;
            emergent-github)
              DEPLOY_ACTOR="${DEPLOY_GITHUB_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_GITHUB_TOKEN}"
              ;;
            emergent-nexus)
              DEPLOY_ACTOR="${DEPLOY_NEXUS_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_NEXUS_TOKEN}"
              ;;
            *)
              ;;
          esac
          printf '%s\n' \
            "deploy_actor=${DEPLOY_ACTOR}" \
            "deploy_token=${DEPLOY_TOKEN}" \
            >> $GITHUB_OUTPUT

      - name: Maven Release with Plugin
        if: ${{ inputs.use-release-plugin }}
        id: maven_release_with_plugin
        uses: emergentdotorg/github-actions/maven-release-classic@v3
        with:
          java-version: ${{ inputs.java-version }}
          maven-profiles: ${{ inputs.maven-profiles }}
          github-actor: ${{ github.actor }}
          github-token: ${{ github.token }}
          deploy-actor: ${{ steps.resolve_vars.outputs.deploy_actor }}
          deploy-token: ${{ steps.resolve_vars.outputs.deploy_token }}
          deploy-server: ${{ inputs.deploy-server }}
          gpg-passphrase: ${{ secrets.maven_gpg_passphrase }}
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}

      - name: Maven Release sans Plugin
        if: ${{ ! inputs.use-release-plugin }}
        id: maven_release_sans_plugin
        uses: emergentdotorg/github-actions/maven-release-gitver@v3
        with:
          java-version: ${{ inputs.java-version }}
          maven-profiles: ${{ inputs.maven-profiles }}
          github-actor: ${{ github.actor }}
          github-token: ${{ github.token }}
          deploy-actor: ${{ steps.resolve_vars.outputs.deploy_actor }}
          deploy-token: ${{ steps.resolve_vars.outputs.deploy_token }}
          deploy-server: ${{ inputs.deploy-server }}
          gpg-passphrase: ${{ secrets.maven_gpg_passphrase }}
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}

      - name: Resolve Version
        id: resolve_version
        shell: bash
        env:
          USE_RELEASE_PLUGIN: ${{ inputs.use-release-plugin }}
          SANS_VERSION: ${{ steps.maven_release_sans_plugin.outputs.version }}
          WITH_VERSION: ${{ steps.maven_release_with_plugin.outputs.version }}
        # language="shell script"
        run: |
          if [[ "${USE_RELEASE_PLUGIN}" = "true" ]]; then
            RELEASE_VERSION="${WITH_VERSION}"
          else
            RELEASE_VERSION="${SANS_VERSION}"
          fi
          printf '%s\n' \
            "release_version=${RELEASE_VERSION}" \
            >> $GITHUB_OUTPUT
