name: Scratch

on:
  workflow_dispatch:
    inputs:
      op:
        description: 'Operation to perform'
        type: choice
        required: false
        default: setup-java
        options:
          - dump-context
          - setup-java

jobs:
  scratch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Dump Context Java
        if: ${{ inputs.op == 'dump-context' }}
        id: dump_context
        uses: emergentdotorg/github-actions/dump-context@v2

      - name: Setup Java
        id: setup_java
        if: ${{ inputs.op == 'setup-java' }}
        uses: emergentdotorg/github-actions/setup-java-env@v2
        with:
          deploy-server: 'central'
          deploy-username-env: CENTRAL_ACTOR
          deploy-password-env: CENTRAL_TOKEN
          github-username-env: GITHUB_ACTOR
          github-password-env: GITHUB_TOKEN
          gpg-passphrase-env: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}

      - name: 'Verify Java and Maven'
        if: ${{ inputs.op == 'setup-java' && success() }}
        shell: bash
        env:
          USER_SETTINGS: ${{ steps.setup_java.outputs.user-settings }}
          USER_TOOLCHAINS: ${{ steps.setup_java.outputs.user-toolchains }}
          GLOBAL_SETTINGS: ${{ steps.setup_java.outputs.global-settings }}
        # language="shell script"
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "JAVA_HOME_8_X64: $JAVA_HOME_8_X64"
          echo "JAVA_HOME_11_X64: $JAVA_HOME_11_X64"
          echo "JAVA_HOME_17_X64: $JAVA_HOME_17_X64"
          mvn -version
          catIfExists() {
            if [ -f "$1" ]; then
              cat "$1"
            else
              echo "WARNING: File $1 does not exist"
            fi
          }
          catIfExists "${USER_SETTINGS}"
          catIfExists "${GLOBAL_SETTINGS}"
          catIfExists "${USER_TOOLCHAINS}"
          catIfExists ${{ github.workspace }}/.git/config
