name: Scratch

on:
  workflow_dispatch:

jobs:
  scratch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        id: setup_java
        uses: emergentdotorg/github-actions/setup-java-env@main
        with:
          deploy-server: 'central'
          deploy-username-env: CENTRAL_ACTOR
          deploy-password-env: CENTRAL_TOKEN
          github-username-env: GITHUB_ACTOR
          github-password-env: GITHUB_TOKEN
          gpg-passphrase-env: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}